services:
  db:
    container_name: postgres-db
    image: postgres:15-alpine
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD", "-f", "http://localhost:5433"]